Added Financial Details Section
leobrod44/Mini-Capstone pull request #186
Opened 2024-03-08 19:40 UTC by Dom-Isbis

The financial details button was added to the condo details page with a toggle function which will, once implemented, toggle the financial component display from "none" to "block" and vice versa.

2024-03-16 10:39 UTC, layanat commented
Toggle looks good. not sure if you want to merge a PR just for this functionality tho?

2024-03-16 10:40 UTC, layanat approved these changes
looks good

2024-03-17 16:42 UTC, mattflahertyy requested changes
looks good just a few things to change and it should be ready

2024-03-17 16:42 UTC, mattflahertyy commented on mini-cap/src/pages/CondoDetails.jsx
> +							{role !== MANAGEMENT_COMPANY && (
change this so that both renter/owners and management companies can see the financial details

2024-03-17 16:42 UTC, mattflahertyy commented on mini-cap/src/pages/CondoDetails.jsx
> +										<>
not sure if it makes a difference  but for equals to use 3 equal signs ===

2024-03-17 21:01 UTC, mattflahertyy approved these changes
everything looks good nice work

2024-03-17 21:01 UTC, merged

2024-03-18 20:29 UTC, leobrod44 commented
Guys none of these commits had any related issue @Dom-Isbis @layanat @mattflahertyy