Us7 t3 condo requests view
leobrod44/Mini-Capstone pull request #211
Opened 2024-03-14 20:46 UTC by mattflahertyy

Only one default request component is shown for each condo. 

BACKEND to implement :
- iterate through each requests PER condo and display these components (inside CondoDetails.jsx)
- add functionality to the CondoRequestsView.jsx to get request data and display
- add functionality to update backend request once company presses advance

2024-03-14 21:00 UTC, leobrod44 requested changes

2024-03-14 21:00 UTC, leobrod44 commented on mini-cap/src/components/CondoRequestsView.jsx
> +        // updateRequest(condoId, requestId);
Go through the upateRequest method and see stepType. The return value while be the step its currently at

2024-03-14 21:00 UTC, leobrod44 commented on mini-cap/src/components/CondoRequestsView.jsx
> +        if (currentStep < 4)
no need to check this, instead check if the updateRequest returns "Completed"

2024-03-14 21:01 UTC, leobrod44 commented
Also, change your commit messages to include the issue number at the end as per code management requirement

2024-03-15 18:48 UTC, laurenrigante reviewed
Ui looks good. 

- i would move the condo requests section ABOVE the edit and delete buttons on the condo details page, i feel like edit and delete should be the last things there
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/1b316300-fc18-4154-bfe4-44678c6162dd)

- i dont think we need a previous button for the requests, i dont think it really makes sense to have one. a mgmt company should only be able to move it forward i dont think they should be able to move it back

- this is a personal opinion, but i think we should change the blue color of  the circles to a blue that matches the rest of the website. The main blue we use is  #4540db , theres also a lighter lbue version we use for titles that  could be an option as well. Here ishow it looks with the blue of the website
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/806a296a-4750-41b0-81c9-d6caf5ea6c28)



- lastly, i think you can make the font size of the writing for request type and description smaller. In comparison to the rest of the condo details writing, its a much larger font.
- 
![image](https://github.com/leobrod44/Mini-Capstone/assets/93160873/e09b560d-08ee-4cb0-a5ff-e4e0e5368ccc)

2024-03-16 14:24 UTC, laurenrigante approved these changes
UI updates look good.

2024-03-18 15:39 UTC, leobrod44 approved these changes

2024-03-18 15:39 UTC, merged